#!/bin/bash

<<PROGRAM_TEXT

This script will rebuild an archive of /home/jana
 if any of the files have been changed or added.

The archive is extracted on a new instance with:

tar -xvzf /mnt/efs/aws-lam1-ubuntu/jana.tgz --directory /home

The following will list files changed since the archive was last rebuilt:

if [ $(find /home/jana -newer \
/mnt/efs/aws-lam1-ubuntu/jana.tgz -print | wc -l) -gt 0 ]
then 
  find /home/jana -newer /mnt/efs/aws-lam1-ubuntu/ubuntu.tgz -print0 \
  | xargs -0 ls -l --time-style=long-iso
fi

PROGRAM_TEXT

if [ $(find /home/jana -newer \
/mnt/efs/aws-lam1-ubuntu/jana.tgz -print | wc -l) -gt 0 ]; then

  echo Recreating the aws-lam1-ubuntu/jana.tgz archive

  rm -f /mnt/efs/aws-lam1-ubuntu/jana.t{gz,xt}

  cd /home
  tar -cvzf /mnt/efs/aws-lam1-ubuntu/jana.tgz jana 2>&1 \
  | tee /mnt/efs/aws-lam1-ubuntu/jana.txt

fi

