#!/bin/sh
#
# 51-LAM-Alaska: This file was created/modified by the Cloud Image build process
# If you no longer want to see this message you can safely remove the file.
echo ""
echo "  This instance is a LAM Alaska machine:"
echo "    http://aws.lam1.us/About http://lam3.freeddns.org"
